### ISSUE TITLE
如果提交的参数有错误的情况下,输出的是HTML而不是json

### ISSUE THREAD

**Issue by Y-A-K-E** [aiChenK/tp6-server#1]
如果严格按照给出的api传入参数是正常的.
```/api/v1/test/param/aaa/bbb```

但是如果少给进参数
```/api/v1/test/param/```

页面会输出HTML错误,而不是JSON.

是不是要ajax请求才会输出json?

**Comment by aiChenK** [comment]
其实我自己项目中是默认输出json的，这里默认输出html只是因为为了保持tp原样
(更改app\ExceptionHandle.php-&gt;render()方法其实就能达到，但是我也会将错误输出json增加到配置中来实现，并且api模块可自定义额外异常实现）

针对你所提到的少给参数报错问题，我会增加对该类异常的捕捉，对提示进行更改
另外给出这个问题最简单的处理方式：

public function param($param1, $param2)
{
    return $this->json([
        'param1' => $param1,
        'param2' => $param2
    ]);
}
// 更改为如下
public function param2($param1 = null, $param2 = null)
{
    if (!$param1 || !$param2) {
        throw new BindParamException('缺少参数');
    }
    return $this->json([
        'param1' => $param1,
        'param2' => $param2
    ]);
}
